### ISSUE TITLE
 minSdkVersion 21

### ISSUE THREAD

**Issue by hishamdubizzle** [harjot-oberai/MaterialShadows#11]
Many thanks for great work.
however, my app supports Android v17 while library minSdkVersion is 21. please help

**Comment by harjot-oberai** [comment]
The library does not build the shadow itself, instead it creates an outline based on the image and passes it on to the Android's inbuilt classes to build the shadow. Since the shadows were introduce in API 21 (Lollipop), it is not possible to lower the min API version.
