### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by linyaDev** [harjot-oberai/MaterialShadows#17]
`  
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@299a81b rejected from java.util.concurrent.ThreadPoolExecutor@c86fdb8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at com.sdsmdg.harjot.materialshadows.shadowutils.ShadowGenerator.calculateAndRenderShadowAsync(ShadowGenerator.java:208)
        at com.sdsmdg.harjot.materialshadows.shadowutils.ShadowGenerator.generate(ShadowGenerator.java:140)
        at com.sdsmdg.harjot.materialshadows.MaterialShadowViewWrapper.onLayout(MaterialShadowViewWrapper.java:91)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)`

**Comment by harjot-oberai** [comment]
Closing for insufficient knowledge
> You may reopen if you can give steps to reproduce etc.

**Comment by zacharee** [comment]
I'm getting this error too. It happens when one of the wrapper layouts is used in a RecyclerView. Scrolling to the end of a long-ish list and then back up causes it.

**Comment by kris1837** [comment]
Same crush. Recycler view with over 100 items. I added shadow in the adapter. My adapter code
```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/uiRootView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        >
    <com.sdsmdg.harjot.materialshadows.MaterialShadowViewWrapper
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:shadowOffsetX="30"
            app:shadowOffsetY="10"
            app:shadowAlpha="0.9"
            >

        <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/uiRow"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/bg_card"
                android:clickable="true"
                android:clipToPadding="false"
                android:focusable="true"
                android:layout_marginStart="16dp"
                android:layout_marginTop="4dp"
                android:layout_marginEnd="16dp"
                android:layout_marginBottom="4dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent">

            <androidx.appcompat.widget.AppCompatTextView
                    android:id="@+id/uiLabel"
                    style="@style/Subtitle"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="12dp"
                    android:layout_marginTop="12dp"
                    android:layout_marginEnd="12dp"
                    android:layout_marginBottom="12dp"
                    android:text="ASfdsf dfas dfas dfasdf sdfasf efasdfse asdf edfwe afef aef"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </com.sdsmdg.harjot.materialshadows.MaterialShadowViewWrapper>
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by princealir** [comment]
Crash occures, when added in an adapter for recyclerview

Java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@e12688a rejected from java.util.concurrent.ThreadPoolExecutor@e6cbefb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
