### ISSUE TITLE
How to wrap API 19?

### ISSUE THREAD

**Issue by wangbax** [harjot-oberai/MaterialShadows#6]
Actually there are many android 4.4. [setOutlineProvider](https://developer.android.com/reference/android/view/View.html#setOutlineProvider(android.view.ViewOutlineProvider)) need API >= 21. 
So, how to wrap low api. thanks. 😊

**Comment by harjot-oberai** [comment]
As far as I know, it is not possible to wrap this for lower APIs as `ViewOutlineProvider` was added in API 21 and it is the core component of the library.
