### ISSUE TITLE
Any possibility to change the color (hue) of the shadow?

### ISSUE THREAD

**Issue by safaorhan** [harjot-oberai/MaterialShadows#7]
I want to change the hue of the shadow. Is it possible?

**Comment by harjot-oberai** [comment]
The library dose not alter any of the code related to Shadow effect generation, it only passes a convex outline. All the shadow effect generation is still handled in the usual way, so no way of changing color of the shadow unless google decides to add this functionality.
I would have loved to add colors to shadows but its just not possible.

You may like to use : [Carbon](https://github.com/ZieIony/Carbon), its an implementation of material design from scratch. It supports shadow color (which also means that google can easily implement it, but they aren't willing for some reason 😞 ) .

**Comment by rayliverified** [comment]
Google :( 🔫
