### ISSUE TITLE
any similar iOS compatible library?

### ISSUE THREAD

**Issue by prscX** [harjot-oberai/MaterialShadows#9]
Hi @harjot-oberai 

First of all I would like to appreciate for open sourcing such a nice library.

Do you any similar library for iOS platform as well?

Thanks
Pranav

**Comment by harjot-oberai** [comment]
Thank you for the appreciation, but I don't think there is any library similar to this for iOS. I am not an iOS developer so can't be sure though. 
A quick google search lead me to [this blog](https://medium.com/@martinblampied/ios-drop-shadows-78edd3f241c1), it might be helpful to you.

**Comment by prscX** [comment]
Thanks @harjot-oberai for the reference

Thanks
Pranav
